// AUTOGENERATED by qs-theme-set from
// ~/.config/theme/templates/niri-theme.kdl.tpl — do not edit directly.
//
// This file owns the niri `layout { … }` block so the focused-window
// border picks up the active theme accent. Included from
// ~/.config/niri/config.kdl via `include`.

layout {
    gaps 10

    center-focused-column "never"

    preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
    }

    default-column-width { proportion 0.5; }

    // Focus ring off — we use a single always-visible `border` that
    // flips colour on focus (Omarchy/Hyprland-style: one 2 px frame).
    focus-ring {
        off
    }

    // Inactive border = the theme's `color8` (ANSI bright-black,
    // i.e. dim neutral — every theme defines one). Originally `#595959aa`
    // hardcoded (Omarchy's literal value); pulling from the palette
    // lets each theme set its own "muted" tone instead of a fixed grey.
    border {
        on
        width 2
        active-color "{{ accent }}"
        inactive-color "{{ color8 }}"
        urgent-color "#9b0000"
    }

    shadow {
        softness 30
        spread 5
        offset x=0 y=5
        color "#0007"
    }

    struts {
    }
}

// Cursor — one family (Capitaine), variant chosen by MODE not by
// theme: nirimaki-theme-set reads the active theme's light.mode marker
// and writes a light (white) cursor for dark themes, a dark (black) one
// for light themes. Same shape either way, so it looks consistent across
// the set. niri uses this for its own pointer AND exports it as
// XCURSOR_THEME/XCURSOR_SIZE to spawned + XWayland clients; theme-set
// also mirrors it into gsettings (GTK) and ~/.icons/default (X11
// fallback) so every surface agrees. Loaded before the user niri files,
// so a `cursor {}` block in ~/.config/niri/* still wins.
cursor {
    xcursor-theme "{{ cursor_theme }}"
    xcursor-size {{ cursor_size }}
}
