#!/usr/bin/env bash
# dev-link.sh — replace the live config paths with symlinks into this
# repo, so editing a file in the repo immediately changes the running
# session. Run once after cloning; idempotent on re-run (after a
# `git pull` you do NOT need to re-run unless new linked dirs were
# added).
#
# What it links:
#   ~/.config/niri/                  → repo/config/niri/
#   ~/.config/quickshell/            → repo/config/quickshell/
#   ~/.config/fish/                  → repo/config/fish/
#   ~/.config/kitty/                 → repo/config/kitty/
#   ~/.config/tmux/                  → repo/config/tmux/
#   ~/.config/nvim/                  → repo/config/nvim/
#   ~/.config/theme/templates/       → repo/config/theme/templates/
#   ~/.config/theme/themes/          → repo/config/theme/themes/
#   ~/.local/bin/qs-<each>           → repo/bin/qs-<each>
#
# What it does NOT touch:
#   ~/.config/theme/current/         — generated by qs-theme-set; the
#                                       active theme is per-machine state
#   ~/.config/niri/config.kdl.bak    — left where it is (gitignored
#                                       anyway, but it sits outside the
#                                       directory we link)
#   ~/.config/quickshell/locale      — user's chosen UI language
#   ~/.local/share/fish/             — fish's runtime state (history,
#                                       universal variables); per-machine
#
# If any of the target paths already exists as a regular file or
# directory (not a symlink to the repo), it is moved to <path>.pre-link
# as a backup before linking. The backup is never deleted by this
# script — clean it up manually after you're sure things work.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sanity: confirm we're in a real nirimaki repo, not some random dir.
for required in config/niri/config.kdl config/quickshell/shell.qml bin/qs-theme-set; do
  if [[ ! -e $REPO_DIR/$required ]]; then
    echo "dev-link.sh: missing $REPO_DIR/$required — refusing to link." >&2
    echo "Run this script from inside the nirimaki repo after files are in place." >&2
    exit 1
  fi
done

# link_path <src-in-repo> <dest-in-home>
# - If $dest is already the right symlink: do nothing.
# - If $dest is a different symlink: replace it.
# - If $dest is a real file/dir: rename to $dest.pre-link, then link.
link_path() {
  local src="$1" dest="$2"

  if [[ -L $dest ]]; then
    local target
    target="$(readlink "$dest")"
    if [[ $target == "$src" ]]; then
      printf '  ok   %s\n' "$dest"
      return
    fi
    printf '  redo %s  (was -> %s)\n' "$dest" "$target"
    rm "$dest"
  elif [[ -e $dest ]]; then
    local backup="${dest}.pre-link"
    if [[ -e $backup ]]; then
      backup="${backup}.$(date +%s)"
    fi
    printf '  back %s  ->  %s\n' "$dest" "$backup"
    mv "$dest" "$backup"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  printf '  link %s  ->  %s\n' "$dest" "$src"
}

echo "== Linking config dirs =="
link_path "$REPO_DIR/config/niri"            "$HOME/.config/niri"
link_path "$REPO_DIR/config/quickshell"      "$HOME/.config/quickshell"
link_path "$REPO_DIR/config/fish"            "$HOME/.config/fish"
link_path "$REPO_DIR/config/kitty"           "$HOME/.config/kitty"
link_path "$REPO_DIR/config/tmux"            "$HOME/.config/tmux"
link_path "$REPO_DIR/config/nvim"            "$HOME/.config/nvim"
mkdir -p "$HOME/.config/theme"
link_path "$REPO_DIR/config/theme/templates" "$HOME/.config/theme/templates"
link_path "$REPO_DIR/config/theme/themes"    "$HOME/.config/theme/themes"

echo "== Linking ~/.local/bin/qs-* helpers =="
mkdir -p "$HOME/.local/bin"
for tool in "$REPO_DIR"/bin/qs-*; do
  [[ -f $tool ]] || continue
  chmod +x "$tool"
  link_path "$tool" "$HOME/.local/bin/$(basename "$tool")"
done

echo
echo "Done."
echo "  - .pre-link backups: $(find "$HOME"/.config "$HOME"/.local/bin -maxdepth 4 -name '*.pre-link*' 2>/dev/null | wc -l) file(s)"
echo "  - Restart quickshell to pick up the linked config: pkill quickshell ; quickshell &"
echo "  - niri auto-reloads on config changes; no restart needed."
