#!/usr/bin/env bash
# dev-link.sh — wire this repo into the live session.
#
# Two flavours of linking:
#   A. Dir-symlink for content that's purely repo-owned (Quickshell,
#      tmux, nvim, theme templates / themes, all `default/...`
#      upgrade-tracked content under ~/.local/share/nirimaki/).
#   B. Per-file seed (COPY, not symlink) for niri's ~/.config/niri/
#      files — they're user-owned after install, so a symlink would
#      send edits back into the repo. Defaults the user can override
#      live under ~/.local/share/nirimaki/default/niri/ instead.
#
# What it links / seeds:
#   ~/.local/share/nirimaki/default/ → repo/default/        (dir symlink)
#   ~/.local/share/nirimaki/bin/     → repo/bin/            (dir symlink)
#   ~/.local/share/nirimaki/plugins/builtin/ → repo/plugins/builtin/  (dir symlink)
#   ~/.config/nirimaki/plugins.json  SEEDED as `{}` once    (user-owned)
#   ~/.config/quickshell/            → repo/config/quickshell/
#   ~/.config/nvim/                  → repo/config/nvim/
#   ~/.config/theme/templates/       → repo/config/theme/templates/
#   ~/.config/theme/themes/          → repo/config/theme/themes/
#   ~/.config/niri/<each>            COPIED from repo/config/niri/<each>
#                                    (only on first run — re-runs leave
#                                     user edits alone)
#   ~/.config/foot/foot.ini          COPIED from repo/config/foot/foot.ini
#                                    (user-owned; theme tracks via internal
#                                     include= directive)
#   ~/.config/tmux/tmux.conf         COPIED from repo/config/tmux/tmux.conf
#                                    (user-owned; no theming layer)
#   ~/.config/fish/config.fish       COPIED from repo/config/fish/config.fish
#                                    (user-owned)
#   ~/.config/fish/{rest}            → repo/config/fish/{rest}
#   ~/.config/nirimaki/{hooks,extensions,themed}/  — per-file samples
#   ~/.local/bin/nirimaki-<each>     → repo/bin/nirimaki-<each>
#
# Also: prunes dangling ~/.local/bin/qs-* symlinks from before the
# Phase-J rename, so PATH no longer contains broken entries.
#
# What it does NOT touch:
#   ~/.config/theme/current/         — generated by nirimaki-theme-set; the
#                                       active theme is per-machine state
#   ~/.config/niri/config.kdl.bak    — left where it is (gitignored
#                                       anyway, but it sits outside the
#                                       directory we link)
#   ~/.config/quickshell/locale      — user's chosen UI language
#   ~/.local/share/fish/             — fish's runtime state (history,
#                                       universal variables); per-machine
#
# If any of the target paths already exists as a regular file or
# directory (not a symlink to the repo), it is moved to <path>.pre-link
# as a backup before linking. The backup is never deleted by this
# script — clean it up manually after you're sure things work.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sanity: confirm we're in a real nirimaki repo, not some random dir.
for required in default/niri/bindings.kdl config/quickshell/shell.qml bin/nirimaki-theme-set; do
  if [[ ! -e $REPO_DIR/$required ]]; then
    echo "dev-link.sh: missing $REPO_DIR/$required — refusing to link." >&2
    echo "Run this script from inside the nirimaki repo after files are in place." >&2
    exit 1
  fi
done

# seed_user_file <src-in-repo> <dest-in-home>
# - If $dest already exists (file, symlink, or otherwise): leave it alone.
# - Otherwise: copy $src to $dest. The file is now user-owned —
#   subsequent `dev-link.sh` runs won't touch it.
seed_user_file() {
  local src="$1" dest="$2"
  if [[ -e $dest || -L $dest ]]; then
    printf '  keep %s\n' "$dest"
    return
  fi
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  printf '  seed %s  <-  %s\n' "$dest" "$src"
}

# link_path <src-in-repo> <dest-in-home>
# - If $dest is already the right symlink: do nothing.
# - If $dest is a different symlink: replace it.
# - If $dest is a real file/dir: rename to $dest.pre-link, then link.
link_path() {
  local src="$1" dest="$2"

  if [[ -L $dest ]]; then
    local target
    target="$(readlink "$dest")"
    if [[ $target == "$src" ]]; then
      printf '  ok   %s\n' "$dest"
      return
    fi
    printf '  redo %s  (was -> %s)\n' "$dest" "$target"
    rm "$dest"
  elif [[ -e $dest ]]; then
    local backup="${dest}.pre-link"
    if [[ -e $backup ]]; then
      backup="${backup}.$(date +%s)"
    fi
    printf '  back %s  ->  %s\n' "$dest" "$backup"
    mv "$dest" "$backup"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  printf '  link %s  ->  %s\n' "$dest" "$src"
}

echo "== Linking repo defaults under ~/.local/share/nirimaki/ =="
# Upgrade-tracked content: niri defaults that the user's ~/.config/niri/
# config.kdl `include`s. install.sh will cp these instead, but in dev
# we symlink so edits show up live.
mkdir -p "$HOME/.local/share/nirimaki"
link_path "$REPO_DIR/default"                "$HOME/.local/share/nirimaki/default"
# Plugin tree: built-ins ship under repo/plugins/ and the loader scans
# ~/.local/share/nirimaki/plugins/builtin/. Plugin QML files use
# `import qs` (Quickshell's native module import) to reach Theme /
# I18n / NiriService — `qs` always resolves to the shell root folder
# regardless of where the importing file lives.
mkdir -p "$HOME/.local/share/nirimaki/plugins"
link_path "$REPO_DIR/plugins/builtin"        "$HOME/.local/share/nirimaki/plugins/builtin"

echo "== Linking purely-repo-owned config dirs =="
link_path "$REPO_DIR/config/quickshell"      "$HOME/.config/quickshell"
link_path "$REPO_DIR/config/nvim"            "$HOME/.config/nvim"
mkdir -p "$HOME/.config/theme"
link_path "$REPO_DIR/config/theme/templates" "$HOME/.config/theme/templates"
link_path "$REPO_DIR/config/theme/themes"    "$HOME/.config/theme/themes"

# Detect a legacy dir-symlink for any of the now-user-owned surfaces
# (niri, fish, foot, tmux). The per-file seed mode below would write
# into the repo through such a symlink and corrupt it. Migration is
# one-time and manual.
for legacy in \
  "$HOME/.config/niri" \
  "$HOME/.config/fish" \
  "$HOME/.config/foot" \
  "$HOME/.config/tmux"; do
  if [[ -L $legacy ]]; then
    target="$(readlink "$legacy")"
    if [[ $target == "$REPO_DIR/"* ]]; then
      echo
      echo "ERROR: $legacy is a legacy dir-symlink (-> $target)" >&2
      echo "       The current dev-link.sh layout needs this as a real" >&2
      echo "       directory so user files can coexist with repo content." >&2
      echo >&2
      echo "       Migrate manually (one time):" >&2
      echo "         mv $legacy ${legacy}.bak-restructure" >&2
      echo "         mkdir -p $legacy" >&2
      echo "         # then re-run dev-link.sh — it will seed the user files" >&2
      echo "         # and re-create the per-element symlinks." >&2
      exit 2
    fi
  fi
done

echo "== Seeding ~/.config/niri/ user files (copy-once, never overwritten) =="
# Repo ships small seed files under config/niri/ that get copied to the
# user's ~/.config/niri/. After the first run these are the user's
# files — edit freely; re-running dev-link.sh leaves them alone.
mkdir -p "$HOME/.config/niri"
for seed in "$REPO_DIR"/config/niri/*.kdl; do
  seed_user_file "$seed" "$HOME/.config/niri/$(basename "$seed")"
done

echo "== Seeding ~/.config/foot/foot.ini (copy-once, never overwritten) =="
# foot.ini is whole-file user-owned (Omarchy convention). Theme
# tracking still works via the `include=~/.config/theme/current/foot.ini`
# directive inside the file — that target IS upgrade-tracked.
mkdir -p "$HOME/.config/foot"
seed_user_file "$REPO_DIR/config/foot/foot.ini" "$HOME/.config/foot/foot.ini"

echo "== Seeding ~/.config/tmux/tmux.conf (copy-once, never overwritten) =="
# tmux.conf is whole-file user-owned. No theming layer — tmux uses
# the terminal ANSI palette directly (Omarchy convention).
mkdir -p "$HOME/.config/tmux"
seed_user_file "$REPO_DIR/config/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"

echo "== Seeding + linking ~/.config/fish/ =="
# config.fish is user-owned (per Omarchy convention — fish loads
# conf.d/* first, then config.fish, so the user file always gets the
# last word). Our content lives entirely in conf.d/, completions/,
# functions/, themes/ — those are symlinked.
mkdir -p "$HOME/.config/fish"
seed_user_file "$REPO_DIR/config/fish/config.fish" "$HOME/.config/fish/config.fish"
for fish_dir in conf.d completions functions themes; do
  [[ -d "$REPO_DIR/config/fish/$fish_dir" ]] || continue
  link_path "$REPO_DIR/config/fish/$fish_dir" "$HOME/.config/fish/$fish_dir"
done
# fish_plugins / fish_variables are runtime state — symlink so fisher's
# updates persist in the repo (dev convenience; install.sh will copy).
for fish_state in fish_plugins fish_variables; do
  [[ -e "$REPO_DIR/config/fish/$fish_state" ]] || continue
  link_path "$REPO_DIR/config/fish/$fish_state" "$HOME/.config/fish/$fish_state"
done

echo "== Pruning stale ~/.local/bin/qs-* symlinks =="
# Phase J renamed bin/qs-* → bin/nirimaki-*. Stale symlinks left over
# from earlier installs are now dangling — clean them so PATH is sane.
shopt -s nullglob
for stale in "$HOME"/.local/bin/qs-*; do
  if [[ -L $stale ]]; then
    printf '  prune %s\n' "$stale"
    rm -- "$stale"
  fi
done
shopt -u nullglob

echo "== Linking ~/.local/bin/nirimaki-* helpers =="
mkdir -p "$HOME/.local/bin"
for tool in "$REPO_DIR"/bin/nirimaki* "$REPO_DIR"/bin/nirimaki; do
  [[ -f $tool ]] || continue
  chmod +x "$tool"
  link_path "$tool" "$HOME/.local/bin/$(basename "$tool")"
done

# User-owned plugin overrides file. Starts as `{}` — only contains
# entries when the user has overridden a plugin's default mount/order
# or disabled one. Settings Menu writes to this file when toggling
# plugins; manual edits are also fine. Per-plugin keys, niri-style
# last-wins on the plugin id (see Plugins.qml header).
echo "== Seeding ~/.config/nirimaki/plugins.json (with comment header) =="
if [[ ! -e "$HOME/.config/nirimaki/plugins.json" ]]; then
  mkdir -p "$HOME/.config/nirimaki"
  cat > "$HOME/.config/nirimaki/plugins.json" <<'EOF'
{
  "_comment": [
    "User plugin overrides — niri-style last-wins per plugin id.",
    "",
    "Format:  { \"<plugin-id>\": <override>, ... }",
    "Override values:",
    "  false                              — disabled (won't load)",
    "  { \"mount\": \"bar.left\" }            — move to a different mount",
    "  { \"after\": \"calendar\" }            — reorder within current mount",
    "  { \"before\": \"updates\" }            — alternative to `after`",
    "",
    "Missing entry → use the manifest defaults from",
    "  ~/.local/share/nirimaki/plugins/builtin/<id>/plugin.json",
    "",
    "Examples:",
    "  \"voxtype\":  false",
    "  \"weather\":  { \"mount\": \"bar.left\", \"after\": \"active-window\" }",
    "  \"calendar\": { \"after\": \"updates\" }",
    "",
    "Open this file via Settings → Setup → Edit → Plugins, or directly:",
    "  nirimaki edit plugins",
    "",
    "Saves take effect immediately — the loader watches the file."
  ]
}
EOF
  printf '  seed %s\n' "$HOME/.config/nirimaki/plugins.json"
else
  printf '  keep %s\n' "$HOME/.config/nirimaki/plugins.json"
fi

# Per-file links into ~/.config/nirimaki/ for hooks samples, the
# menu.json sample, and the themed README. Per-file (not whole-dir)
# because user-added active hooks / overrides live in the same dirs
# alongside our samples — we don't want a symlinked-dir to swallow
# the whole tree under repo ownership.
echo "== Linking ~/.config/nirimaki/ samples =="
shopt -s globstar nullglob
for sample in "$REPO_DIR"/config/nirimaki/**/*; do
  [[ -f $sample ]] || continue
  rel="${sample#$REPO_DIR/config/nirimaki/}"
  dest="$HOME/.config/nirimaki/$rel"
  mkdir -p "$(dirname "$dest")"
  link_path "$sample" "$dest"
done
shopt -u globstar nullglob

# .desktop launchers for repo-owned entries (Install Web App / Remove
# Web App / future Nirimaki menu items). Linked per-file rather than
# linking the whole dir because user-installed webapps' .desktops live
# in the same ~/.local/share/applications/ alongside these.
echo "== Linking ~/.local/share/applications/*.desktop =="
mkdir -p "$HOME/.local/share/applications"
shopt -s nullglob
for desktop in "$REPO_DIR"/config/applications/*.desktop; do
  link_path "$desktop" "$HOME/.local/share/applications/$(basename "$desktop")"
done
shopt -u nullglob

echo
echo "Done."
echo "  - .pre-link backups: $(find "$HOME"/.config "$HOME"/.local/bin -maxdepth 4 -name '*.pre-link*' 2>/dev/null | wc -l) file(s)"
echo "  - Restart quickshell to pick up the linked config: pkill quickshell ; quickshell &"
echo "  - niri auto-reloads on config changes; no restart needed."
